name: publish

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload jar to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-sources.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: publish jar
        env:
          modrinth_key: ${{ secrets.MODRINTH_KEY }}
          changelog: ${{ github.event.release.body }}
        run: ./gradlew publish publishUnified --stacktrace --no-daemon
